spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=employee_app
spring.datasource.password=employee123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway (since you already use db migration)
spring.flyway.enabled=true
spring.flyway.schemas=EMPLOYEE_APP
spring.flyway.user=employee_app
spring.flyway.password=employee123
